"""Pluecker diagnostics for four thermodynamic response channels.

The pair-vector order is (12, 13, 14, 23, 24, 34). A decomposable
two-form in four dimensions satisfies b12*b34 - b13*b24 + b14*b23 = 0.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Sequence

import numpy as np
from numpy.typing import NDArray

PAIR_ORDER = ("12", "13", "14", "23", "24", "34")


@dataclass(frozen=True)
class PluckerTestResult:
    status: str
    residual: float
    standard_error: float | None
    z_score: float | None
    z_threshold: float | None
    normalized_residual: float
    pair_order: tuple[str, ...] = PAIR_ORDER
    note: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _vector(values: Sequence[float], expected: int, name: str) -> NDArray[np.float64]:
    array = np.asarray(values, dtype=float)
    if array.shape != (expected,):
        raise ValueError(f"{name} must have shape ({expected},), got {array.shape}")
    if not np.all(np.isfinite(array)):
        raise ValueError(f"{name} contains non-finite values")
    return array


def pairs_from_gradients(
    u: Sequence[float], v: Sequence[float]
) -> NDArray[np.float64]:
    """Return the six brackets generated by two common gradient vectors."""
    u_vec = _vector(u, 4, "u")
    v_vec = _vector(v, 4, "v")
    return np.array(
        [
            u_vec[0] * v_vec[1] - v_vec[0] * u_vec[1],
            u_vec[0] * v_vec[2] - v_vec[0] * u_vec[2],
            u_vec[0] * v_vec[3] - v_vec[0] * u_vec[3],
            u_vec[1] * v_vec[2] - v_vec[1] * u_vec[2],
            u_vec[1] * v_vec[3] - v_vec[1] * u_vec[3],
            u_vec[2] * v_vec[3] - v_vec[2] * u_vec[3],
        ],
        dtype=float,
    )


def skew_matrix_from_pairs(pairs: Sequence[float]) -> NDArray[np.float64]:
    """Build the 4x4 skew matrix associated with the ordered pair vector."""
    b12, b13, b14, b23, b24, b34 = _vector(pairs, 6, "pairs")
    return np.array(
        [
            [0.0, b12, b13, b14],
            [-b12, 0.0, b23, b24],
            [-b13, -b23, 0.0, b34],
            [-b14, -b24, -b34, 0.0],
        ],
        dtype=float,
    )


def plucker_residual(pairs: Sequence[float]) -> float:
    """Evaluate b12*b34 - b13*b24 + b14*b23."""
    b12, b13, b14, b23, b24, b34 = _vector(pairs, 6, "pairs")
    return float(b12 * b34 - b13 * b24 + b14 * b23)


def plucker_gradient(pairs: Sequence[float]) -> NDArray[np.float64]:
    """Gradient of the Pluecker polynomial in PAIR_ORDER coordinates."""
    b12, b13, b14, b23, b24, b34 = _vector(pairs, 6, "pairs")
    return np.array([b34, -b24, b23, b14, -b13, b12], dtype=float)


def normalized_residual(pairs: Sequence[float], floor: float = 1e-30) -> float:
    """Dimensionless residual |P| / ||b||^2."""
    b = _vector(pairs, 6, "pairs")
    denominator = max(float(np.dot(b, b)), floor)
    return abs(plucker_residual(b)) / denominator


def delta_method_variance(
    pairs: Sequence[float], covariance: Sequence[Sequence[float]]
) -> float:
    """First-order variance of the residual for an independent six-channel estimate."""
    b = _vector(pairs, 6, "pairs")
    cov = np.asarray(covariance, dtype=float)
    if cov.shape != (6, 6):
        raise ValueError(f"covariance must have shape (6, 6), got {cov.shape}")
    if not np.all(np.isfinite(cov)):
        raise ValueError("covariance contains non-finite values")
    if not np.allclose(cov, cov.T, rtol=1e-10, atol=1e-12):
        raise ValueError("covariance must be symmetric")
    eigenvalues = np.linalg.eigvalsh(cov)
    scale = max(1.0, float(np.max(np.abs(eigenvalues))))
    if float(np.min(eigenvalues)) < -1e-10 * scale:
        raise ValueError("covariance must be positive semidefinite")
    gradient = plucker_gradient(b)
    variance = float(gradient @ cov @ gradient)
    return max(variance, 0.0)


def common_gradient_control(
    u: Sequence[float],
    v: Sequence[float],
    *,
    tolerance: float = 1e-12,
) -> PluckerTestResult:
    """Audit the algebraic control B = u v^T - v u^T.

    This is an implementation check, not an empirical falsification test.
    """
    pairs = pairs_from_gradients(u, v)
    residual = plucker_residual(pairs)
    status = "PASS_CONTROL" if abs(residual) <= tolerance else "FAIL_CONTROL"
    return PluckerTestResult(
        status=status,
        residual=residual,
        standard_error=None,
        z_score=None,
        z_threshold=None,
        normalized_residual=normalized_residual(pairs),
        note=(
            "Common-gradient construction is decomposable by definition; "
            "passing this control cannot validate the physical hypothesis."
        ),
    )


def independent_bracket_test(
    pairs: Sequence[float],
    covariance: Sequence[Sequence[float]],
    *,
    z_threshold: float = 5.0,
    variance_floor: float = 1e-30,
) -> PluckerTestResult:
    """Test six independently estimated brackets against decomposability.

    The covariance must describe the six-channel estimate in PAIR_ORDER.
    A five-sigma default is deliberately conservative because numerical
    differentiation and cross-study systematics are rarely polite.
    """
    if not np.isfinite(z_threshold) or z_threshold <= 0:
        raise ValueError("z_threshold must be positive and finite")
    b = _vector(pairs, 6, "pairs")
    residual = plucker_residual(b)
    variance = delta_method_variance(b, covariance)
    if variance <= variance_floor:
        return PluckerTestResult(
            status="INCONCLUSIVE_UNCERTAINTY_MODEL",
            residual=residual,
            standard_error=None,
            z_score=None,
            z_threshold=z_threshold,
            normalized_residual=normalized_residual(b),
            note="Residual uncertainty is zero or numerically unresolved.",
        )

    standard_error = float(np.sqrt(variance))
    z_score = abs(residual) / standard_error
    status = (
        "FALSIFIED_MEASUREMENT_CONTRACT"
        if z_score > z_threshold
        else "NOT_FALSIFIED"
    )
    return PluckerTestResult(
        status=status,
        residual=residual,
        standard_error=standard_error,
        z_score=z_score,
        z_threshold=z_threshold,
        normalized_residual=normalized_residual(b),
        note=(
            "The verdict applies to the frozen conjunction of chart, channels, "
            "provenance, calibration, and uncertainty model."
        ),
    )


def paper_gradient_error_bound(
    measured_pairs: Sequence[float],
    epsilon_u: float,
    epsilon_v: float,
    measured_u_norm: float,
    measured_v_norm: float,
) -> float:
    """Reproduce the deterministic bound stated in the paper.

    When measured_pairs is itself formed from one common measured u and v,
    its exact Pluecker residual is algebraically zero. The bound remains a
    perturbation guarantee, but not a nontrivial empirical test.
    """
    values = (epsilon_u, epsilon_v, measured_u_norm, measured_v_norm)
    if any((not np.isfinite(value) or value < 0) for value in values):
        raise ValueError("error bounds and norms must be finite and nonnegative")
    b = _vector(measured_pairs, 6, "measured_pairs")
    error_frobenius = 2.0 * (
        epsilon_u * measured_v_norm
        + epsilon_v * measured_u_norm
        + 3.0 * epsilon_u * epsilon_v
    )
    eta = error_frobenius / np.sqrt(2.0)
    return float(np.linalg.norm(b) * eta + 1.5 * eta * eta)
